### ISSUE TITLE
modified pbtx.proto

### ISSUE THREAD

**Issue by ssinyagin** [fixpayments/pbtx_android#6]
Probably by mistake, but I noticed that this definition is different from the one in the original pbtx.proto:

```
enum KeyType {
    EKIS_KEY = 0;
}
```

Please make sure you have an exact copy of https://github.com/fixpayments/pbtx/blob/master/pbtx.proto without modifications

**Comment by vavadiyahiren** [comment]
In the defined proto there is Esoio key are you sure you wanted to change it back to that name ?

![image](https://user-images.githubusercontent.com/5488223/159406087-87989519-cc39-41c6-9087-097b9bdd2758.png)
